### PR TITLE
Fixed release script build var setting & added test to prevent regression

### LINKED ISSUE #488: TFV version output incorrect
I noticed that the tfv version output seems to be `dev` as opposed to semver for some of the latest releases.  I tried a few of the latest 0.12.x.

```
terraform-validator  version
Build version: dev
```

I checked 0.11.0 which worked as expected.
```
./terraform-validator  version
Build version: v0.11.0
```

### PR DESCRIPTION
**Pull request by melinath**
Resolved #488

### CODE REVIEW

File: release.sh [hunk 1]
```diff
@@ -56,6 +56,20 @@ for platform in ${platforms}; do
 
 		echo "Building ${binary_name} v${version} for platform ${platform} / arch ${arch}..."
 		GO111MODULE=on GOOS=${platform} GOARCH=${arch} CGO_ENABLED=0 go build -ldflags "${ldflags}" -o "${release_dir}/${binary_name}" .
+		if [[ "$platform" == "darwin" && "${arch}" == "amd64" ]]; then
```
Comment (iyabchen) [inline release.sh:59]: why windows does not need the test?

**Review by iyabchen — APPROVED** [review]

File: release.sh (hunk 1 above)
Comment (melinath) [reply release.sh:59]: If this works for one of the builds, it should work for all of them - and also, this is expected to be run on `darwin amd64` so the other binaries would fail to run.
