### PR TITLE
Fixed GetOk / GetOkExists behavior

### LINKED ISSUE #113: Error: converting tfplan to CAI assets: .. Error resolving image name ''"
**What do I see?**
When running a policy validate on our terraform, we get the following error.

`Error: converting tfplan to CAI assets: converting resource google_compute_disk: converting asset: Error resolving image name '': Error checking if image exists: json: invalid use of ,string struct tag, trying to unmarshal "projects/acmck-02-sandbox/global/images/" into uint64`

**What do I expect**
The policy validation  to output a violation(s) or report "No Violations".

**Reproduce**
Attach a disk to GCE instance with no image defined

```
resource "google_compute_disk" "bastion-disk" {
  name = "${var.name}-disk"
  type = "pd-ssd"
  zone = "us-central1-a"
  size = 100
}
```

and attach inside the instance resource:

```
    attached_disk {
      source      = google_compute_disk.bastion-disk.self_link
  }
```

**versions**

```
bash-5.0# terraform version
Terraform v0.12.16
+ provider.google v2.17.0
+ provider.google-beta v2.20.0
+ provider.kubernetes v1.10.0
+ provider.null v2.1.2
+ provider.random v2.2.1

Your version of Terraform is out of date! The latest version
is 0.12.17. You can update by downloading from https://www.terraform.io/downloads.html

bash-5.0# terraform-validator version
Build version: 2019-11-07
```
Happens on alpine or debain base image based containers.

```
bash-5.0# uname -a
Linux 9a1661522e53 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 Linux
```

### PR DESCRIPTION
**Pull request by melinath**
Resolved #113. Made FakeResourceData behave more consistently with Terraform core in terms of the values it produces. This ensures that expanders written with Terraform [ResourceData](https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/resource_data.go) structs in mind behave properly in TFV as well.

Some test data had to be updated due to the code now properly excluding empty data.

I'm sorry for the long PR; most of it is new tests.

### CODE REVIEW

File: converters/google/fake_resource_data.go [hunk 1]
```diff
@@ -43,6 +58,36 @@ func (d *FakeResourceData) Id() string {
...
+		s = schemaPath[len(schemaPath)-1]
+	}
+	if r.Value == nil && s != nil {
+		r.Value = r.ValueOrZero(s)
+	}
+
+	return getResult{
+		Value: r.Value,
+		Computed: r.Computed,
+		Exists: r.Exists,
```
Comment (ScottSuarez) [inline converters/google/fake_resource_data.go:86]: will this ever be false? I don't really understand how this reader is working

Comment (melinath) [reply converters/google/fake_resource_data.go:86]: r is the result from reading the field - Exists would be false if the field isn't set in the underlying data.

**Review by ScottSuarez — APPROVED** [review]

**Review by slevenick — APPROVED** [review]
Seems reasonable to me! Good to have this better represent normal Terraform functionality
